from collections.abc import Mapping
from typing import Any

class Metafields: ...
class Events: ...

class Countable:
    @classmethod
    def count(cls, _options: None = ..., **kwargs: Mapping[str, Any]) -> int: ...
